<?php

namespace App\Models;

use App\Mail\PostCreated;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Mail;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ["blog_id", "title", "description"];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function blog()
    {
        return $this->belongsTo(Blog::class);
    }

    public function url()
    {
        return config("app.url")."/community/posts/".$this->id;
    }
}
